{% set name = "optuna" %}
{% set version = "0.11.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46609265828cc2e3abe485e00d8b3e98b30a6e7ec2f2564961d363849f428b2e

build:
  number: 0
  entry_points:
    - optuna = optuna.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - alembic
    - cliff
    - colorlog
    - numpy
    - pandas
    - pip
    - python
    - scipy
    - six
    - sqlalchemy >=1.1.0
    - typing
  run:
    - alembic
    - cliff
    - colorlog
    - numpy
    - pandas
    - python
    - scipy
    - six
    - sqlalchemy >=1.1.0
    - typing

test:
  imports:
    - optuna
    - optuna.integration
    - optuna.pruners
    - optuna.samplers
    - optuna.samplers.tpe
    - optuna.storages
    - optuna.storages.rdb
    - optuna.testing
    - tests
    - tests.integration_tests
    - tests.pruners_tests
    - tests.samplers_tests
    - tests.storages_tests
    - tests.storages_tests.rdb_tests
  commands:
    - optuna --help
  requires:
    - bokeh
    - chainer >=5.0.0
    - keras
    - lightgbm
    - mock
    - mpi4py
    - mxnet
    - plotly
    - pytest
    - tensorflow
    - xgboost

about:
  home: https://optuna.org/
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: Summary of the package
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
